# Generated by Django 4.0.4 on 2022-04-22 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workouts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout', models.CharField(max_length=250)),
                ('programs', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('video', models.FileField(max_length=30, upload_to='')),
                ('preview', models.FileField(max_length=30, upload_to='')),
                ('diet1', models.CharField(max_length=250)),
                ('diet2', models.CharField(max_length=250)),
                ('diet_photo', models.ImageField(upload_to='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trainer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.trainer')),
            ],
            options={
                'verbose_name_plural': 'workouts',
            },
        ),
    ]
